# Port descriptions from Wikipedia
source = "https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers"

common_ports = [
{'Port': 0, 'Description': 'In programming APIs (not in communication between hosts), requests a system-allocated (dynamic) port[6]'},
{'Port': 1, 'Description': 'TCP Port Service Multiplexer (TCPMUX). Historic. Both TCP and UDP have been assigned to TCPMUX by IANA,[2] but by design only TCP is specified.[7]'},
{'Port': 2, 'Description': 'compressnet (Management Utility)'},
{'Port': 3, 'Description': 'compressnet (Compression Process)'},
{'Port': 5, 'Description': 'Remote Job Entry[8] was historically using socket 5 in its old socket form, while MIB PIM has identified it as TCP/5[9] and IANA has assigned both TCP and UDP 5 to it.'},
{'Port': 7, 'Description': 'Echo Protocol[10][11]'},
{'Port': 9, 'Description': 'Discard Protocol[13]'},
{'Port': 11, 'Description': 'Active Users (systat service)[15][16]'},
{'Port': 13, 'Description': 'Daytime Protocol[17]'},
{'Port': 15, 'Description': 'Previously netstat service[2][15]'},
{'Port': 17, 'Description': 'Quote of the Day (QOTD)[18]'},
{'Port': 18, 'Description': 'Message Send Protocol[19][20]'},
{'Port': 19, 'Description': 'Character Generator Protocol (CHARGEN)[21]'},
{'Port': 20, 'Description': 'File Transfer Protocol (FTP) data transfer[11]'},
{'Port': 21, 'Description': 'File Transfer Protocol (FTP) control (command)[11][12][22][23]'},
{'Port': 22, 'Description': 'Secure Shell (SSH),[11] secure logins, file transfers (scp, sftp) and port forwarding'},
{'Port': 23, 'Description': 'Telnet protocol—unencrypted text communications[11][24]'},
{'Port': 25, 'Description': 'Simple Mail Transfer Protocol (SMTP),[11][25] used for email routing between mail servers'},
{'Port': 27, 'Description': 'NSW User System FE'},
{'Port': 28, 'Description': "Palo Alto Networks' Panorama High Availability (HA) sync encrypted port.[26]"},
{'Port': 29, 'Description': 'MSG ICP'},
{'Port': 31, 'Description': 'MSG Authentication'},
{'Port': 33, 'Description': 'Display Support Protocol'},
{'Port': 37, 'Description': 'Time Protocol[27]'},
{'Port': 38, 'Description': 'Route Access Protocol'},
{'Port': 39, 'Description': 'Resource Location Protocol'},
{'Port': 41, 'Description': 'Graphics'},
{'Port': 42, 'Description': 'Host Name Server Protocol[28]'},
{'Port': 43, 'Description': 'WHOIS protocol[29][30][31]'},
{'Port': 44, 'Description': 'MPM FLAGS Protocol'},
{'Port': 45, 'Description': 'MPM (recv)'},
{'Port': 46, 'Description': 'MPM (default send)'},
{'Port': 47, 'Description': ''},
{'Port': 48, 'Description': 'Digital Audit Daemon'},
{'Port': 49, 'Description': 'TACACS Login Host protocol.[32] TACACS+, still in draft which is an improved but distinct version of TACACS, only uses TCP 49.[33]'},
{'Port': 50, 'Description': 'Remote Mail Checking Protocol'},
{'Port': 51, 'Description': 'Historically used for Interface Message Processor logical address management,[34] entry has been removed by IANA on 2013-05-25'},
{'Port': 52, 'Description': 'Xerox Network Systems (XNS) Time Protocol. Despite this port being assigned by IANA, the service is meant to work on SPP (ancestor of IPX/SPX), instead of TCP/IP.[35]'},
{'Port': 53, 'Description': 'Domain Name System (DNS)[36][11]'},
{'Port': 54, 'Description': 'Xerox Network Systems (XNS) Clearinghouse (Name Server). Despite this port being assigned by IANA, the service is meant to work on SPP (ancestor of IPX/SPX), instead of TCP/IP.[35]'},
{'Port': 55, 'Description': 'ISI Graphics Language'},
{'Port': 56, 'Description': 'Xerox Network Systems (XNS) Authentication Protocol. Despite this port being assigned by IANA, the service is meant to work on SPP (ancestor of IPX/SPX), instead of TCP/IP.[35]'},
{'Port': 58, 'Description': 'Xerox Network Systems (XNS) Mail. Despite this port being assigned by IANA, the service is meant to work on SPP (ancestor of IPX/SPX), instead of TCP/IP.[35]'},
{'Port': 61, 'Description': "Historically assigned to the NIFTP-Based Mail protocol,[37] but was never documented in the related IEN.[38] The port number entry was removed from IANA's registry on 2017-05-18.[2]"},
{'Port': 62, 'Description': 'ACA Services'},
{'Port': 63, 'Description': 'whois++'},
{'Port': 64, 'Description': 'covia'},
{'Port': 65, 'Description': 'TACACS-Database Service'},
{'Port': 66, 'Description': 'Oracle SQL*NET'},
{'Port': 67, 'Description': 'Bootstrap Protocol (BOOTP) server;[11] also used by Dynamic Host Configuration Protocol (DHCP)'},
{'Port': 68, 'Description': 'Bootstrap Protocol (BOOTP) client;[11] also used by Dynamic Host Configuration Protocol (DHCP)'},
{'Port': 69, 'Description': 'Trivial File Transfer Protocol (TFTP)[11][39][40][41]'},
{'Port': 70, 'Description': 'Gopher protocol[42]'},
{'Port': 71, 'Description': 'NETRJS protocol[43][44][45]'},
{'Port': 72, 'Description': 'NETRJS protocol[43][44][45]'},
{'Port': 73, 'Description': 'NETRJS protocol[43][44][45]'},
{'Port': 74, 'Description': 'NETRJS protocol[43][44][45]'},
{'Port': 76, 'Description': 'Distributed External Object Store'},
{'Port': 78, 'Description': 'vettcp'},
{'Port': 79, 'Description': 'Finger protocol[11][46][47]'},
{'Port': 80, 'Description': 'Hypertext Transfer Protocol (HTTP)[48][49] uses TCP in versions 1.x and 2. HTTP/3 uses QUIC,[50] a transport protocol on top of UDP.'},
{'Port': 81, 'Description': 'TorPark onion routing[verification needed]'},
{'Port': 82, 'Description': 'TorPark control[verification needed]'},
{'Port': 83, 'Description': 'MIT ML Device, networking file system[51]'},
{'Port': 84, 'Description': 'Common Trace Facility'},
{'Port': 85, 'Description': 'MIT ML Device'},
{'Port': 86, 'Description': 'Micro Focus Cobol'},
{'Port': 88, 'Description': 'Kerberos[11][52][53] authentication system'},
{'Port': 89, 'Description': 'SU/MIT Telnet Gateway'},
{'Port': 90, 'Description': 'PointCast (dotcom)[2]'},
{'Port': 91, 'Description': 'MIT Dover Spooler'},
{'Port': 92, 'Description': 'Network Printing Protocol'},
{'Port': 93, 'Description': 'Device Control Protocol'},
{'Port': 94, 'Description': 'Tivoli Object Dispatcher'},
{'Port': 95, 'Description': 'SUPDUP, terminal-independent remote login[54]'},
{'Port': 96, 'Description': 'DIXIE Protocol'},
{'Port': 97, 'Description': 'Swift Remote Virtual File Protocol'},
{'Port': 98, 'Description': 'TAC News'},
{'Port': 99, 'Description': 'Metagram Relay'},
{'Port': 101, 'Description': 'NIC host name[55]'},
{'Port': 102, 'Description': 'ISO Transport Service Access Point (TSAP) Class 0 protocol;[56][57]'},
{'Port': 103, 'Description': 'Genesis Point-to-Point Trans Net'},
{'Port': 104, 'Description': 'Digital Imaging and Communications in Medicine (DICOM; also port 11112)'},
{'Port': 105, 'Description': 'CCSO Nameserver[58]'},
{'Port': 106, 'Description': 'macOS Server, (macOS) password server[11]'},
{'Port': 107, 'Description': 'Remote User Telnet Service (RTelnet)[59]'},
{'Port': 108, 'Description': 'IBM Systems Network Architecture (SNA) gateway access server'},
{'Port': 109, 'Description': 'Post Office Protocol, version 2 (POP2)[60]'},
{'Port': 110, 'Description': 'Post Office Protocol, version 3 (POP3)[11][61][62]'},
{'Port': 111, 'Description': 'Open Network Computing Remote Procedure Call (ONC RPC, sometimes referred to as Sun RPC)'},
{'Port': 112, 'Description': 'McIDAS Data Transmission Protocol'},
{'Port': 113, 'Description': 'Ident, authentication service/identification protocol,[11][63] used by IRC servers to identify users'},
{'Port': 115, 'Description': 'Simple File Transfer Protocol[65]'},
{'Port': 116, 'Description': 'ANSA REX Notify'},
{'Port': 117, 'Description': 'UUCP Mapping Project (path service)[citation needed]'},
{'Port': 118, 'Description': 'Structured Query Language (SQL) Services[jargon]'},
{'Port': 119, 'Description': 'Network News Transfer Protocol (NNTP),[11] retrieval of newsgroup messages[66][67]'},
{'Port': 120, 'Description': 'CFDPTKT'},
{'Port': 121, 'Description': 'Encore Expedited Remote Pro.Call'},
{'Port': 122, 'Description': 'SMAKYNET'},
{'Port': 123, 'Description': 'Network Time Protocol (NTP), used for time synchronization[11]'},
{'Port': 124, 'Description': 'ANSA REX Trader'},
{'Port': 125, 'Description': 'Locus PC-Interface Net Map Ser'},
{'Port': 126, 'Description': "Formerly Unisys Unitary Login, renamed by Unisys to NXEdit. Used by Unisys Programmer's Workbench for Clearpath MCP, an IDE for Unisys MCP software development"},
{'Port': 127, 'Description': 'Locus PC-Interface Conn Server'},
{'Port': 128, 'Description': 'GSS X License Verification'},
{'Port': 129, 'Description': 'Password Generator Protocol'},
{'Port': 130, 'Description': 'Cisco FNATIVE'},
{'Port': 131, 'Description': 'Cisco TNATIVE'},
{'Port': 132, 'Description': 'Cisco SYSMAINT'},
{'Port': 133, 'Description': 'Statistics Service (statsrv)'},
{'Port': 134, 'Description': 'INGRES-NET Service'},
{'Port': 135, 'Description': 'DCE endpoint resolution'},
{'Port': 136, 'Description': 'PROFILE Naming System'},
{'Port': 137, 'Description': 'NetBIOS Name Service, used for name registration and resolution[69][70]'},
{'Port': 138, 'Description': 'NetBIOS Datagram Service[11][69][70]'},
{'Port': 139, 'Description': 'NetBIOS Session Service[69][70]'},
{'Port': 140, 'Description': 'EMFIS Data Service'},
{'Port': 141, 'Description': 'EMFIS Control Service'},
{'Port': 142, 'Description': 'Britton-Lee IDM'},
{'Port': 143, 'Description': 'Internet Message Access Protocol (IMAP),[11] management of electronic mail messages on a server[71]'},
{'Port': 144, 'Description': 'Universal Management Architecture'},
{'Port': 145, 'Description': 'UAAC Protocol'},
{'Port': 146, 'Description': 'ISO-IP0'},
{'Port': 147, 'Description': 'ISO-IP'},
{'Port': 148, 'Description': 'Jargon'},
{'Port': 149, 'Description': 'AED 512 Emulation Service'},
{'Port': 150, 'Description': 'SQL-NET'},
{'Port': 151, 'Description': 'HEMS'},
{'Port': 152, 'Description': 'Background File Transfer Program (BFTP)[72][importance?]'},
{'Port': 153, 'Description': 'Simple Gateway Monitoring Protocol (SGMP), a protocol for remote inspection and alteration of gateway management information[73]'},
{'Port': 154, 'Description': 'netsc-prod'},
{'Port': 155, 'Description': 'netsc-dev'},
{'Port': 156, 'Description': 'Structured Query Language (SQL) Service[jargon]'},
{'Port': 157, 'Description': 'KNET/VM Command/Message Protocol'},
{'Port': 158, 'Description': 'Distributed Mail System Protocol (DMSP, sometimes referred to as Pcmail)[74][importance?]'},
{'Port': 159, 'Description': 'NSS-Routing'},
{'Port': 160, 'Description': 'SGMP-TRAPS'},
{'Port': 161, 'Description': 'Simple Network Management Protocol (SNMP)[75][citation needed][11]'},
{'Port': 162, 'Description': 'Simple Network Management Protocol Trap (SNMPTRAP)[75][76][citation needed]'},
{'Port': 163, 'Description': 'CMIP/TCP Manager'},
{'Port': 164, 'Description': 'CMIP/TCP Agent'},
{'Port': 165, 'Description': 'Xerox'},
{'Port': 166, 'Description': 'Sirius Systems'},
{'Port': 167, 'Description': 'NAMP[disambiguation needed]'},
{'Port': 168, 'Description': 'RSVD'},
{'Port': 169, 'Description': 'SEND'},
{'Port': 170, 'Description': 'Network PostScript print server'},
{'Port': 171, 'Description': 'Network Innovations Multiplex'},
{'Port': 172, 'Description': 'Network Innovations CL/1'},
{'Port': 173, 'Description': 'Xyplex'},
{'Port': 174, 'Description': 'MAILQ'},
{'Port': 175, 'Description': 'VMNET'},
{'Port': 176, 'Description': 'GENRAD-MUX'},
{'Port': 177, 'Description': 'X Display Manager Control Protocol (XDMCP), used for remote logins to an X Display Manager server[77][self-published source]'},
{'Port': 178, 'Description': 'NextStep Window Server'},
{'Port': 179, 'Description': 'Border Gateway Protocol (BGP),[78] used to exchange routing and reachability information among autonomous systems (AS) on the Internet'},
{'Port': 180, 'Description': 'ris'},
{'Port': 181, 'Description': 'Unify[disambiguation needed]'},
{'Port': 182, 'Description': 'Unisys Audit SITP'},
{'Port': 183, 'Description': 'OCBinder'},
{'Port': 184, 'Description': 'OCServer'},
{'Port': 185, 'Description': 'Remote-KIS'},
{'Port': 186, 'Description': 'KIS Protocol'},
{'Port': 187, 'Description': 'Application Communication Interface'},
{'Port': 188, 'Description': "Plus Five's MUMPS"},
{'Port': 189, 'Description': 'Queued File Transport'},
{'Port': 190, 'Description': 'Gateway Access Control Protocol'},
{'Port': 191, 'Description': 'Prospero Directory Service'},
{'Port': 192, 'Description': 'OSU Network Monitoring System'},
{'Port': 193, 'Description': 'Spider Remote Monitoring Protocol'},
{'Port': 194, 'Description': 'Internet Relay Chat (IRC)[79]'},
{'Port': 195, 'Description': 'DNSIX Network Layer Module Audit'},
{'Port': 196, 'Description': 'DNSIX Session Mgt Module Audit Redir'},
{'Port': 197, 'Description': 'Directory Location Service'},
{'Port': 198, 'Description': 'Directory Location Service Monitor'},
{'Port': 199, 'Description': 'SNMP Unix Multiplexer (SMUX)[80]'},
{'Port': 200, 'Description': 'IBM System Resource Controller'},
{'Port': 201, 'Description': 'AppleTalk Routing Maintenance'},
{'Port': 209, 'Description': 'Quick Mail Transfer Protocol[81][self-published source]'},
{'Port': 210, 'Description': 'ANSI Z39.50'},
{'Port': 213, 'Description': 'Internetwork Packet Exchange (IPX)'},
{'Port': 218, 'Description': 'Message posting protocol (MPP)'},
{'Port': 220, 'Description': 'Internet Message Access Protocol (IMAP), version 3'},
{'Port': 225, 'Description': 'Reserved'},
{'Port': 226, 'Description': 'Reserved'},
{'Port': 227, 'Description': 'Reserved'},
{'Port': 228, 'Description': 'Reserved'},
{'Port': 229, 'Description': 'Reserved'},
{'Port': 230, 'Description': 'Reserved'},
{'Port': 231, 'Description': 'Reserved'},
{'Port': 232, 'Description': 'Reserved'},
{'Port': 233, 'Description': 'Reserved'},
{'Port': 234, 'Description': 'Reserved'},
{'Port': 235, 'Description': 'Reserved'},
{'Port': 236, 'Description': 'Reserved'},
{'Port': 237, 'Description': 'Reserved'},
{'Port': 238, 'Description': 'Reserved'},
{'Port': 239, 'Description': 'Reserved'},
{'Port': 240, 'Description': 'Reserved'},
{'Port': 241, 'Description': 'Reserved'},
{'Port': 249, 'Description': 'Reserved'},
{'Port': 250, 'Description': 'Reserved'},
{'Port': 251, 'Description': 'Reserved'},
{'Port': 252, 'Description': 'Reserved'},
{'Port': 253, 'Description': 'Reserved'},
{'Port': 254, 'Description': 'Reserved'},
{'Port': 255, 'Description': 'Reserved'},
{'Port': 259, 'Description': 'Efficient Short Remote Operations (ESRO)'},
{'Port': 262, 'Description': 'Arcisdms'},
{'Port': 264, 'Description': 'Border Gateway Multicast Protocol (BGMP)'},
{'Port': 280, 'Description': 'http-mgmt'},
{'Port': 300, 'Description': 'ThinLinc Web Access'},
{'Port': 308, 'Description': 'Novastor Online Backup'},
{'Port': 311, 'Description': 'macOS Server Admin[11] (officially AppleShare IP Web administration[2])'},
{'Port': 312, 'Description': 'macOS Xsan administration[11]'},
{'Port': 318, 'Description': 'PKIX Time Stamp Protocol (TSP)'},
{'Port': 319, 'Description': 'Precision Time Protocol (PTP) event messages'},
{'Port': 320, 'Description': 'Precision Time Protocol (PTP) general messages'},
{'Port': 350, 'Description': 'Mapping of Airline Traffic over Internet Protocol (MATIP) type A'},
{'Port': 351, 'Description': 'MATIP type B'},
{'Port': 356, 'Description': 'cloanto-net-1 (used by Cloanto Amiga Explorer and VMs)'},
{'Port': 366, 'Description': 'On-Demand Mail Relay (ODMR)'},
{'Port': 369, 'Description': 'Rpc2portmap'},
{'Port': 370, 'Description': 'codaauth2, Coda authentication server'},
{'Port': 371, 'Description': 'ClearCase albd'},
{'Port': 376, 'Description': 'Amiga Envoy Network Inquiry Protocol'},
{'Port': 383, 'Description': 'HP data alarm manager'},
{'Port': 384, 'Description': 'A Remote Network Server System'},
{'Port': 387, 'Description': 'AURP (AppleTalk Update-based Routing Protocol)[83]'},
{'Port': 388, 'Description': 'Unidata LDM near real-time data distribution protocol[84][self-published source][85][self-published source]'},
{'Port': 389, 'Description': 'Lightweight Directory Access Protocol (LDAP)[11]'},
{'Port': 399, 'Description': 'Digital Equipment Corporation DECnet+ (Phase V) over TCP/IP (RFC1859)'},
{'Port': 401, 'Description': 'Uninterruptible power supply (UPS)'},
{'Port': 427, 'Description': 'Service Location Protocol (SLP)[11]'},
{'Port': 433, 'Description': 'NNTP, part of Network News Transfer Protocol'},
{'Port': 434, 'Description': 'Mobile IP Agent (RFC 5944)'},
{'Port': 443, 'Description': 'Hypertext Transfer Protocol Secure (HTTPS)[48][49] uses TCP in versions 1.x and 2. HTTP/3 uses QUIC,[50] a transport protocol on top of UDP.'},
{'Port': 444, 'Description': 'Simple Network Paging Protocol (SNPP), RFC 1568'},
{'Port': 445, 'Description': 'Microsoft-DS (Directory Services) Active Directory,[86] Windows shares'},
{'Port': 464, 'Description': 'Kerberos Change/Set password'},
{'Port': 465, 'Description': 'SMTP over implicit SSL (obsolete)[87]'},
{'Port': 475, 'Description': 'tcpnethaspsrv, Aladdin Knowledge Systems Hasp services'},
{'Port': 476, 'Description': 'Centro Software ERP ports'},
{'Port': 477, 'Description': 'Centro Software ERP ports'},
{'Port': 478, 'Description': 'Centro Software ERP ports'},
{'Port': 479, 'Description': 'Centro Software ERP ports'},
{'Port': 480, 'Description': 'Centro Software ERP ports'},
{'Port': 481, 'Description': 'Centro Software ERP ports'},
{'Port': 482, 'Description': 'Centro Software ERP ports'},
{'Port': 483, 'Description': 'Centro Software ERP ports'},
{'Port': 484, 'Description': 'Centro Software ERP ports'},
{'Port': 485, 'Description': 'Centro Software ERP ports'},
{'Port': 486, 'Description': 'Centro Software ERP ports'},
{'Port': 487, 'Description': 'Centro Software ERP ports'},
{'Port': 488, 'Description': 'Centro Software ERP ports'},
{'Port': 489, 'Description': 'Centro Software ERP ports'},
{'Port': 490, 'Description': 'Centro Software ERP ports'},
{'Port': 491, 'Description': 'GO-Global remote access and application publishing software'},
{'Port': 497, 'Description': 'Retrospect'},
{'Port': 500, 'Description': 'Internet Security Association and Key Management Protocol (ISAKMP) / Internet Key Exchange (IKE)[11]'},
{'Port': 502, 'Description': 'Modbus Protocol'},
{'Port': 504, 'Description': 'Citadel, multiservice protocol for dedicated clients for the Citadel groupware system'},
{'Port': 510, 'Description': 'FirstClass Protocol (FCP), used by FirstClass client/server groupware system'},
{'Port': 512, 'Description': 'Rexec, Remote Process Execution'},
{'Port': 513, 'Description': 'rlogin'},
{'Port': 514, 'Description': 'Remote Shell, used to execute non-interactive commands on a remote system (Remote Shell, rsh, remsh)'},
{'Port': 515, 'Description': 'Line Printer Daemon (LPD),[11] print service'},
{'Port': 517, 'Description': 'Talk'},
{'Port': 518, 'Description': 'NTalk'},
{'Port': 520, 'Description': 'efs, extended file name server'},
{'Port': 521, 'Description': 'Routing Information Protocol Next Generation (RIPng)'},
{'Port': 524, 'Description': 'NetWare Core Protocol (NCP) is used for a variety things such as access to primary NetWare server resources, Time Synchronization, etc.'},
{'Port': 525, 'Description': 'Timed, Timeserver'},
{'Port': 530, 'Description': 'Remote procedure call (RPC)'},
{'Port': 532, 'Description': 'netnews[11]'},
{'Port': 533, 'Description': 'netwall, for emergency broadcasts'},
{'Port': 540, 'Description': 'Unix-to-Unix Copy Protocol (UUCP)'},
{'Port': 542, 'Description': 'commerce (Commerce Applications)'},
{'Port': 543, 'Description': 'klogin, Kerberos login'},
{'Port': 544, 'Description': 'kshell, Kerberos Remote shell'},
{'Port': 546, 'Description': 'DHCPv6 client'},
{'Port': 547, 'Description': 'DHCPv6 server'},
{'Port': 548, 'Description': 'Apple Filing Protocol (AFP) over TCP[11]'},
{'Port': 550, 'Description': 'new-rwho, new-who[90]'},
{'Port': 554, 'Description': 'Real Time Streaming Protocol (RTSP)[11]'},
{'Port': 556, 'Description': 'Remotefs, RFS, rfs_server'},
{'Port': 560, 'Description': 'rmonitor, Remote Monitor'},
{'Port': 561, 'Description': 'monitor'},
{'Port': 563, 'Description': 'NNTP over TLS/SSL (NNTPS)'},
{'Port': 564, 'Description': '9P (Plan 9)'},
{'Port': 585, 'Description': 'Previously assigned for use of Internet Message Access Protocol over TLS/SSL (IMAPS), now deregisterd in favour of port 993.[91]'},
{'Port': 587, 'Description': 'email message submission[11][92] (SMTP)'},
{'Port': 591, 'Description': 'FileMaker 6.0 (and later) Web Sharing (HTTP Alternate, also see port 80)'},
{'Port': 593, 'Description': 'HTTP RPC Ep Map, Remote procedure call over Hypertext Transfer Protocol, often used by Distributed Component Object Model services and Microsoft Exchange Server'},
{'Port': 601, 'Description': 'Reliable Syslog Service — used for system logging'},
{'Port': 604, 'Description': 'TUNNEL profile,[93] a protocol for BEEP peers to form an application layer tunnel'},
{'Port': 623, 'Description': 'ASF Remote Management and Control Protocol (ASF-RMCP) & IPMI Remote Management Protocol'},
{'Port': 625, 'Description': 'Open Directory Proxy (ODProxy)[11]'},
{'Port': 631, 'Description': 'Internet Printing Protocol (IPP)[11]'},
{'Port': 635, 'Description': 'RLZ DBase'},
{'Port': 636, 'Description': 'Lightweight Directory Access Protocol over TLS/SSL (LDAPS)[11]'},
{'Port': 639, 'Description': 'Multicast Source Discovery Protocol, MSDP'},
{'Port': 641, 'Description': 'SupportSoft Nexus Remote Command (control/listening), a proxy gateway connecting remote control traffic'},
{'Port': 643, 'Description': 'SANity'},
{'Port': 646, 'Description': 'Label Distribution Protocol (LDP), a routing protocol used in MPLS networks'},
{'Port': 647, 'Description': 'DHCP Failover protocol[94]'},
{'Port': 648, 'Description': 'Registry Registrar Protocol (RRP)[95]'},
{'Port': 651, 'Description': 'IEEE-MMS'},
{'Port': 653, 'Description': 'SupportSoft Nexus Remote Command (data), a proxy gateway connecting remote control traffic'},
{'Port': 654, 'Description': 'Media Management System (MMS) Media Management Protocol (MMP)[96]'},
{'Port': 655, 'Description': 'Tinc VPN daemon'},
{'Port': 657, 'Description': 'IBM RMC (Remote monitoring and Control) protocol, used by System p5 AIX Integrated Virtualization Manager (IVM)[97] and Hardware Management Console to connect managed logical partitions (LPAR) to enable dynamic partition reconfiguration'},
{'Port': 660, 'Description': 'macOS Server administration,[2] version 10.4 and earlier[11]'},
{'Port': 666, 'Description': 'Doom, the first online first-person shooter'},
{'Port': 674, 'Description': 'Application Configuration Access Protocol (ACAP)'},
{'Port': 688, 'Description': 'REALM-RUSD (ApplianceWare Server Appliance Management Protocol)'},
{'Port': 690, 'Description': 'Velneo Application Transfer Protocol (VATP)'},
{'Port': 691, 'Description': 'MS Exchange Routing'},
{'Port': 694, 'Description': 'Linux-HA high-availability heartbeat'},
{'Port': 695, 'Description': 'IEEE Media Management System over SSL (IEEE-MMS-SSL)[98]'},
{'Port': 698, 'Description': 'Optimized Link State Routing (OLSR)'},
{'Port': 700, 'Description': 'Extensible Provisioning Protocol (EPP), a protocol for communication between domain name registries and registrars (RFC 5734)'},
{'Port': 701, 'Description': 'Link Management Protocol (LMP),[99] a protocol that runs between a pair of nodes and is used to manage traffic engineering (TE) links'},
{'Port': 702, 'Description': 'IRIS[100][101] (Internet Registry Information Service) over BEEP (Blocks Extensible Exchange Protocol)[102] (RFC 3983)'},
{'Port': 706, 'Description': 'Secure Internet Live Conferencing (SILC)'},
{'Port': 711, 'Description': 'Cisco Tag Distribution Protocol[103][104][105]—being replaced by the MPLS Label Distribution Protocol[106]'},
{'Port': 712, 'Description': 'Topology Broadcast based on Reverse-Path Forwarding routing protocol (TBRPF; RFC 3684)'},
{'Port': 749, 'Description': 'Kerberos administration[11]'},
{'Port': 750, 'Description': 'kerberos-iv, Kerberos version IV'},
{'Port': 751, 'Description': 'kerberos_master, Kerberos authentication'},
{'Port': 752, 'Description': 'passwd_server, Kerberos password (kpasswd) server'},
{'Port': 753, 'Description': 'Reverse Routing Header (RRH)[107]'},
{'Port': 754, 'Description': 'tell send'},
{'Port': 760, 'Description': 'krbupdate [kreg], Kerberos registration'},
{'Port': 782, 'Description': 'Conserver serial-console management server'},
{'Port': 783, 'Description': 'SpamAssassin spamd daemon'},
{'Port': 800, 'Description': 'mdbs-daemon'},
{'Port': 802, 'Description': 'MODBUS/TCP Security[108]'},
{'Port': 808, 'Description': 'Microsoft Net.TCP Port Sharing Service'},
{'Port': 829, 'Description': 'Certificate Management Protocol[109]'},
{'Port': 830, 'Description': 'NETCONF over SSH'},
{'Port': 831, 'Description': 'NETCONF over BEEP'},
{'Port': 832, 'Description': 'NETCONF for SOAP over HTTPS'},
{'Port': 833, 'Description': 'NETCONF for SOAP over BEEP'},
{'Port': 843, 'Description': 'Adobe Flash[110]'},
{'Port': 847, 'Description': 'DHCP Failover protocol'},
{'Port': 848, 'Description': 'Group Domain Of Interpretation (GDOI) protocol'},
{'Port': 853, 'Description': 'DNS over TLS (RFC 7858)'},
{'Port': 860, 'Description': 'iSCSI (RFC 3720)'},
{'Port': 861, 'Description': 'OWAMP control (RFC 4656)'},
{'Port': 862, 'Description': 'TWAMP control (RFC 5357)'},
{'Port': 873, 'Description': 'rsync file synchronization protocol'},
{'Port': 888, 'Description': 'cddbp, CD DataBase (CDDB) protocol (CDDBP)'},
{'Port': 897, 'Description': 'Brocade SMI-S RPC'},
{'Port': 898, 'Description': 'Brocade SMI-S RPC SSL'},
{'Port': 902, 'Description': 'VMware ESXi[112][113]'},
{'Port': 903, 'Description': 'VMware ESXi[112][113]'},
{'Port': 953, 'Description': 'BIND remote name daemon control (RNDC)[114][115]'},
{'Port': 981, 'Description': 'Remote HTTPS management for firewall devices running embedded Check Point VPN-1 software[116]'},
{'Port': 987, 'Description': 'Sony PlayStation Wake On Lan'},
{'Port': 988, 'Description': 'Lustre (file system)[118] Protocol (data).'},
{'Port': 989, 'Description': 'FTPS Protocol (data), FTP over TLS/SSL'},
{'Port': 990, 'Description': 'FTPS Protocol (control), FTP over TLS/SSL'},
{'Port': 991, 'Description': 'Netnews Administration System (NAS)[119]'},
{'Port': 992, 'Description': 'Telnet protocol over TLS/SSL'},
{'Port': 993, 'Description': 'Internet Message Access Protocol over TLS/SSL (IMAPS)[11]'},
{'Port': 994, 'Description': 'Previously assigned to Internet Relay Chat over TLS/SSL (IRCS), but was not used in common practice.'},
{'Port': 995, 'Description': 'Post Office Protocol 3 over TLS/SSL (POP3S)[11]'},
{'Port': 1010, 'Description': 'ThinLinc web-based administration interface[120]'},
{'Port': 1011, 'Description': 'Reserved'},
{'Port': 1012, 'Description': 'Reserved'},
{'Port': 1013, 'Description': 'Reserved'},
{'Port': 1014, 'Description': 'Reserved'},
{'Port': 1015, 'Description': 'Reserved'},
{'Port': 1016, 'Description': 'Reserved'},
{'Port': 1017, 'Description': 'Reserved'},
{'Port': 1018, 'Description': 'Reserved'},
{'Port': 1019, 'Description': 'Reserved'},
{'Port': 1020, 'Description': 'Reserved'},
{'Port': 1023, 'Description': 'z/OS Network File System (NFS) (potentially ports 991–1023'}
]